name: Clippy Check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  clippy:
    name: Run Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          profile: minimal
          override: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libdbus-1-dev \
            libpipewire-0.3-dev \
            libavutil-dev \
            libavformat-dev \
            libavcodec-dev \
            libswscale-dev \
            libavdevice-dev \
            libavfilter-dev \
            pkg-config

      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

